# Generated by Django 4.0.1 on 2022-08-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.CharField(max_length=50),
        ),
    ]
